// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface AddExerciseRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.AddExerciseResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 workout_exercise_id = 1;</code>
   * @return The workoutExerciseId.
   */
  long getWorkoutExerciseId();
}
