// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

/**
 * Protobuf type {@code org.example.proto.CreateTrainingReq}
 */
public final class CreateTrainingReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.proto.CreateTrainingReq)
    CreateTrainingReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      CreateTrainingReq.class.getName());
  }
  // Use CreateTrainingReq.newBuilder() to construct.
  private CreateTrainingReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateTrainingReq() {
    category_ = "";
    exercises_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.Trainings.internal_static_org_example_proto_CreateTrainingReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.Trainings.internal_static_org_example_proto_CreateTrainingReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.CreateTrainingReq.class, org.example.proto.CreateTrainingReq.Builder.class);
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
  private long accountId_ = 0L;
  /**
   * <code>int64 account_id = 1;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public long getAccountId() {
    return accountId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int CATEGORY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <code>string category = 3;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <code>string category = 3;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXERCISES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<org.example.proto.CreateExercise> exercises_;
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.proto.CreateExercise> getExercisesList() {
    return exercises_;
  }
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.proto.CreateExerciseOrBuilder> 
      getExercisesOrBuilderList() {
    return exercises_;
  }
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  @java.lang.Override
  public int getExercisesCount() {
    return exercises_.size();
  }
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  @java.lang.Override
  public org.example.proto.CreateExercise getExercises(int index) {
    return exercises_.get(index);
  }
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  @java.lang.Override
  public org.example.proto.CreateExerciseOrBuilder getExercisesOrBuilder(
      int index) {
    return exercises_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accountId_ != 0L) {
      output.writeInt64(1, accountId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, category_);
    }
    for (int i = 0; i < exercises_.size(); i++) {
      output.writeMessage(4, exercises_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, accountId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, category_);
    }
    for (int i = 0; i < exercises_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, exercises_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.CreateTrainingReq)) {
      return super.equals(obj);
    }
    org.example.proto.CreateTrainingReq other = (org.example.proto.CreateTrainingReq) obj;

    if (getAccountId()
        != other.getAccountId()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (!getExercisesList()
        .equals(other.getExercisesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    if (getExercisesCount() > 0) {
      hash = (37 * hash) + EXERCISES_FIELD_NUMBER;
      hash = (53 * hash) + getExercisesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.CreateTrainingReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.proto.CreateTrainingReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.proto.CreateTrainingReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.CreateTrainingReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.CreateTrainingReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.proto.CreateTrainingReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.proto.CreateTrainingReq)
      org.example.proto.CreateTrainingReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_CreateTrainingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_CreateTrainingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.CreateTrainingReq.class, org.example.proto.CreateTrainingReq.Builder.class);
    }

    // Construct using org.example.proto.CreateTrainingReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accountId_ = 0L;
      timestamp_ = 0L;
      category_ = "";
      if (exercisesBuilder_ == null) {
        exercises_ = java.util.Collections.emptyList();
      } else {
        exercises_ = null;
        exercisesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.Trainings.internal_static_org_example_proto_CreateTrainingReq_descriptor;
    }

    @java.lang.Override
    public org.example.proto.CreateTrainingReq getDefaultInstanceForType() {
      return org.example.proto.CreateTrainingReq.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.CreateTrainingReq build() {
      org.example.proto.CreateTrainingReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.CreateTrainingReq buildPartial() {
      org.example.proto.CreateTrainingReq result = new org.example.proto.CreateTrainingReq(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.proto.CreateTrainingReq result) {
      if (exercisesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          exercises_ = java.util.Collections.unmodifiableList(exercises_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.exercises_ = exercises_;
      } else {
        result.exercises_ = exercisesBuilder_.build();
      }
    }

    private void buildPartial0(org.example.proto.CreateTrainingReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accountId_ = accountId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.category_ = category_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.CreateTrainingReq) {
        return mergeFrom((org.example.proto.CreateTrainingReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.CreateTrainingReq other) {
      if (other == org.example.proto.CreateTrainingReq.getDefaultInstance()) return this;
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (exercisesBuilder_ == null) {
        if (!other.exercises_.isEmpty()) {
          if (exercises_.isEmpty()) {
            exercises_ = other.exercises_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureExercisesIsMutable();
            exercises_.addAll(other.exercises_);
          }
          onChanged();
        }
      } else {
        if (!other.exercises_.isEmpty()) {
          if (exercisesBuilder_.isEmpty()) {
            exercisesBuilder_.dispose();
            exercisesBuilder_ = null;
            exercises_ = other.exercises_;
            bitField0_ = (bitField0_ & ~0x00000008);
            exercisesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetExercisesFieldBuilder() : null;
          } else {
            exercisesBuilder_.addAllMessages(other.exercises_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              accountId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              org.example.proto.CreateExercise m =
                  input.readMessage(
                      org.example.proto.CreateExercise.parser(),
                      extensionRegistry);
              if (exercisesBuilder_ == null) {
                ensureExercisesIsMutable();
                exercises_.add(m);
              } else {
                exercisesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long accountId_ ;
    /**
     * <code>int64 account_id = 1;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>int64 account_id = 1;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {

      accountId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 account_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accountId_ = 0L;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <code>string category = 3;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category = 3;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category = 3;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string category = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string category = 3;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<org.example.proto.CreateExercise> exercises_ =
      java.util.Collections.emptyList();
    private void ensureExercisesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        exercises_ = new java.util.ArrayList<org.example.proto.CreateExercise>(exercises_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.proto.CreateExercise, org.example.proto.CreateExercise.Builder, org.example.proto.CreateExerciseOrBuilder> exercisesBuilder_;

    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public java.util.List<org.example.proto.CreateExercise> getExercisesList() {
      if (exercisesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(exercises_);
      } else {
        return exercisesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public int getExercisesCount() {
      if (exercisesBuilder_ == null) {
        return exercises_.size();
      } else {
        return exercisesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public org.example.proto.CreateExercise getExercises(int index) {
      if (exercisesBuilder_ == null) {
        return exercises_.get(index);
      } else {
        return exercisesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder setExercises(
        int index, org.example.proto.CreateExercise value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.set(index, value);
        onChanged();
      } else {
        exercisesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder setExercises(
        int index, org.example.proto.CreateExercise.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.set(index, builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder addExercises(org.example.proto.CreateExercise value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.add(value);
        onChanged();
      } else {
        exercisesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder addExercises(
        int index, org.example.proto.CreateExercise value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.add(index, value);
        onChanged();
      } else {
        exercisesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder addExercises(
        org.example.proto.CreateExercise.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.add(builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder addExercises(
        int index, org.example.proto.CreateExercise.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.add(index, builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder addAllExercises(
        java.lang.Iterable<? extends org.example.proto.CreateExercise> values) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, exercises_);
        onChanged();
      } else {
        exercisesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder clearExercises() {
      if (exercisesBuilder_ == null) {
        exercises_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        exercisesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public Builder removeExercises(int index) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.remove(index);
        onChanged();
      } else {
        exercisesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public org.example.proto.CreateExercise.Builder getExercisesBuilder(
        int index) {
      return internalGetExercisesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public org.example.proto.CreateExerciseOrBuilder getExercisesOrBuilder(
        int index) {
      if (exercisesBuilder_ == null) {
        return exercises_.get(index);  } else {
        return exercisesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public java.util.List<? extends org.example.proto.CreateExerciseOrBuilder> 
         getExercisesOrBuilderList() {
      if (exercisesBuilder_ != null) {
        return exercisesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(exercises_);
      }
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public org.example.proto.CreateExercise.Builder addExercisesBuilder() {
      return internalGetExercisesFieldBuilder().addBuilder(
          org.example.proto.CreateExercise.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public org.example.proto.CreateExercise.Builder addExercisesBuilder(
        int index) {
      return internalGetExercisesFieldBuilder().addBuilder(
          index, org.example.proto.CreateExercise.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
     */
    public java.util.List<org.example.proto.CreateExercise.Builder> 
         getExercisesBuilderList() {
      return internalGetExercisesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.proto.CreateExercise, org.example.proto.CreateExercise.Builder, org.example.proto.CreateExerciseOrBuilder> 
        internalGetExercisesFieldBuilder() {
      if (exercisesBuilder_ == null) {
        exercisesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.example.proto.CreateExercise, org.example.proto.CreateExercise.Builder, org.example.proto.CreateExerciseOrBuilder>(
                exercises_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        exercises_ = null;
      }
      return exercisesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.example.proto.CreateTrainingReq)
  }

  // @@protoc_insertion_point(class_scope:org.example.proto.CreateTrainingReq)
  private static final org.example.proto.CreateTrainingReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.CreateTrainingReq();
  }

  public static org.example.proto.CreateTrainingReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTrainingReq>
      PARSER = new com.google.protobuf.AbstractParser<CreateTrainingReq>() {
    @java.lang.Override
    public CreateTrainingReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTrainingReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTrainingReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.CreateTrainingReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

