// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

/**
 * Protobuf type {@code org.example.proto.CreateExercise}
 */
public final class CreateExercise extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.proto.CreateExercise)
    CreateExerciseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      CreateExercise.class.getName());
  }
  // Use CreateExercise.newBuilder() to construct.
  private CreateExercise(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateExercise() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.Trainings.internal_static_org_example_proto_CreateExercise_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.Trainings.internal_static_org_example_proto_CreateExercise_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.CreateExercise.class, org.example.proto.CreateExercise.Builder.class);
  }

  public static final int SORT_ID_FIELD_NUMBER = 1;
  private long sortId_ = 0L;
  /**
   * <code>int64 sort_id = 1;</code>
   * @return The sortId.
   */
  @java.lang.Override
  public long getSortId() {
    return sortId_;
  }

  public static final int EXERCISE_ID_FIELD_NUMBER = 2;
  private long exerciseId_ = 0L;
  /**
   * <code>int64 exercise_id = 2;</code>
   * @return The exerciseId.
   */
  @java.lang.Override
  public long getExerciseId() {
    return exerciseId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sortId_ != 0L) {
      output.writeInt64(1, sortId_);
    }
    if (exerciseId_ != 0L) {
      output.writeInt64(2, exerciseId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sortId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sortId_);
    }
    if (exerciseId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, exerciseId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.CreateExercise)) {
      return super.equals(obj);
    }
    org.example.proto.CreateExercise other = (org.example.proto.CreateExercise) obj;

    if (getSortId()
        != other.getSortId()) return false;
    if (getExerciseId()
        != other.getExerciseId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SORT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSortId());
    hash = (37 * hash) + EXERCISE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExerciseId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.CreateExercise parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.CreateExercise parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.CreateExercise parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.CreateExercise parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.CreateExercise parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.CreateExercise parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.CreateExercise parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.CreateExercise parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.proto.CreateExercise parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.proto.CreateExercise parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.CreateExercise parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.CreateExercise parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.CreateExercise prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.proto.CreateExercise}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.proto.CreateExercise)
      org.example.proto.CreateExerciseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_CreateExercise_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_CreateExercise_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.CreateExercise.class, org.example.proto.CreateExercise.Builder.class);
    }

    // Construct using org.example.proto.CreateExercise.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sortId_ = 0L;
      exerciseId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.Trainings.internal_static_org_example_proto_CreateExercise_descriptor;
    }

    @java.lang.Override
    public org.example.proto.CreateExercise getDefaultInstanceForType() {
      return org.example.proto.CreateExercise.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.CreateExercise build() {
      org.example.proto.CreateExercise result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.CreateExercise buildPartial() {
      org.example.proto.CreateExercise result = new org.example.proto.CreateExercise(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.proto.CreateExercise result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sortId_ = sortId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.exerciseId_ = exerciseId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.CreateExercise) {
        return mergeFrom((org.example.proto.CreateExercise)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.CreateExercise other) {
      if (other == org.example.proto.CreateExercise.getDefaultInstance()) return this;
      if (other.getSortId() != 0L) {
        setSortId(other.getSortId());
      }
      if (other.getExerciseId() != 0L) {
        setExerciseId(other.getExerciseId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sortId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              exerciseId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long sortId_ ;
    /**
     * <code>int64 sort_id = 1;</code>
     * @return The sortId.
     */
    @java.lang.Override
    public long getSortId() {
      return sortId_;
    }
    /**
     * <code>int64 sort_id = 1;</code>
     * @param value The sortId to set.
     * @return This builder for chaining.
     */
    public Builder setSortId(long value) {

      sortId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sort_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSortId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sortId_ = 0L;
      onChanged();
      return this;
    }

    private long exerciseId_ ;
    /**
     * <code>int64 exercise_id = 2;</code>
     * @return The exerciseId.
     */
    @java.lang.Override
    public long getExerciseId() {
      return exerciseId_;
    }
    /**
     * <code>int64 exercise_id = 2;</code>
     * @param value The exerciseId to set.
     * @return This builder for chaining.
     */
    public Builder setExerciseId(long value) {

      exerciseId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 exercise_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExerciseId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      exerciseId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.example.proto.CreateExercise)
  }

  // @@protoc_insertion_point(class_scope:org.example.proto.CreateExercise)
  private static final org.example.proto.CreateExercise DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.CreateExercise();
  }

  public static org.example.proto.CreateExercise getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateExercise>
      PARSER = new com.google.protobuf.AbstractParser<CreateExercise>() {
    @java.lang.Override
    public CreateExercise parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateExercise> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateExercise> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.CreateExercise getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

