// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface CreateExerciseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.CreateExercise)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sort_id = 1;</code>
   * @return The sortId.
   */
  long getSortId();

  /**
   * <code>int64 exercise_id = 2;</code>
   * @return The exerciseId.
   */
  long getExerciseId();
}
