// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface CreateTrainingReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.CreateTrainingReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 account_id = 1;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string category = 3;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 3;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  java.util.List<org.example.proto.CreateExercise> 
      getExercisesList();
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  org.example.proto.CreateExercise getExercises(int index);
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  int getExercisesCount();
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  java.util.List<? extends org.example.proto.CreateExerciseOrBuilder> 
      getExercisesOrBuilderList();
  /**
   * <code>repeated .org.example.proto.CreateExercise exercises = 4;</code>
   */
  org.example.proto.CreateExerciseOrBuilder getExercisesOrBuilder(
      int index);
}
