// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.Empty)
    com.google.protobuf.MessageOrBuilder {
}
