// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface GetTrainingReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.GetTrainingReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 account_id = 3;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <pre>
   * single day
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * single day
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
   * @return The range.
   */
  org.example.proto.GetTrainingReq.TimestampRange getRange();
  /**
   * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
   */
  org.example.proto.GetTrainingReq.TimestampRangeOrBuilder getRangeOrBuilder();

  org.example.proto.GetTrainingReq.FilterCase getFilterCase();
}
