// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface GetTrainingRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.GetTrainingResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  java.util.List<org.example.proto.GetTrainingResp.Training> 
      getTrainingsList();
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  org.example.proto.GetTrainingResp.Training getTrainings(int index);
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  int getTrainingsCount();
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  java.util.List<? extends org.example.proto.GetTrainingResp.TrainingOrBuilder> 
      getTrainingsOrBuilderList();
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  org.example.proto.GetTrainingResp.TrainingOrBuilder getTrainingsOrBuilder(
      int index);
}
