// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

/**
 * Protobuf type {@code org.example.proto.GetTrainingReq}
 */
public final class GetTrainingReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.proto.GetTrainingReq)
    GetTrainingReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GetTrainingReq.class.getName());
  }
  // Use GetTrainingReq.newBuilder() to construct.
  private GetTrainingReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetTrainingReq() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.GetTrainingReq.class, org.example.proto.GetTrainingReq.Builder.class);
  }

  public interface TimestampRangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.proto.GetTrainingReq.TimestampRange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 from = 1;</code>
     * @return The from.
     */
    long getFrom();

    /**
     * <code>int64 to = 2;</code>
     * @return The to.
     */
    long getTo();
  }
  /**
   * Protobuf type {@code org.example.proto.GetTrainingReq.TimestampRange}
   */
  public static final class TimestampRange extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.proto.GetTrainingReq.TimestampRange)
      TimestampRangeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        TimestampRange.class.getName());
    }
    // Use TimestampRange.newBuilder() to construct.
    private TimestampRange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TimestampRange() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_TimestampRange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_TimestampRange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.GetTrainingReq.TimestampRange.class, org.example.proto.GetTrainingReq.TimestampRange.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private long from_ = 0L;
    /**
     * <code>int64 from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public long getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private long to_ = 0L;
    /**
     * <code>int64 to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public long getTo() {
      return to_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0L) {
        output.writeInt64(1, from_);
      }
      if (to_ != 0L) {
        output.writeInt64(2, to_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, from_);
      }
      if (to_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, to_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.GetTrainingReq.TimestampRange)) {
        return super.equals(obj);
      }
      org.example.proto.GetTrainingReq.TimestampRange other = (org.example.proto.GetTrainingReq.TimestampRange) obj;

      if (getFrom()
          != other.getFrom()) return false;
      if (getTo()
          != other.getTo()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrom());
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTo());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.proto.GetTrainingReq.TimestampRange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.proto.GetTrainingReq.TimestampRange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.GetTrainingReq.TimestampRange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.GetTrainingReq.TimestampRange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.proto.GetTrainingReq.TimestampRange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.proto.GetTrainingReq.TimestampRange)
        org.example.proto.GetTrainingReq.TimestampRangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_TimestampRange_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_TimestampRange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.GetTrainingReq.TimestampRange.class, org.example.proto.GetTrainingReq.TimestampRange.Builder.class);
      }

      // Construct using org.example.proto.GetTrainingReq.TimestampRange.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        from_ = 0L;
        to_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_TimestampRange_descriptor;
      }

      @java.lang.Override
      public org.example.proto.GetTrainingReq.TimestampRange getDefaultInstanceForType() {
        return org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.GetTrainingReq.TimestampRange build() {
        org.example.proto.GetTrainingReq.TimestampRange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.GetTrainingReq.TimestampRange buildPartial() {
        org.example.proto.GetTrainingReq.TimestampRange result = new org.example.proto.GetTrainingReq.TimestampRange(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.proto.GetTrainingReq.TimestampRange result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.from_ = from_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.to_ = to_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.GetTrainingReq.TimestampRange) {
          return mergeFrom((org.example.proto.GetTrainingReq.TimestampRange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.GetTrainingReq.TimestampRange other) {
        if (other == org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance()) return this;
        if (other.getFrom() != 0L) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0L) {
          setTo(other.getTo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                from_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                to_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long from_ ;
      /**
       * <code>int64 from = 1;</code>
       * @return The from.
       */
      @java.lang.Override
      public long getFrom() {
        return from_;
      }
      /**
       * <code>int64 from = 1;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(long value) {

        from_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = 0L;
        onChanged();
        return this;
      }

      private long to_ ;
      /**
       * <code>int64 to = 2;</code>
       * @return The to.
       */
      @java.lang.Override
      public long getTo() {
        return to_;
      }
      /**
       * <code>int64 to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(long value) {

        to_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.proto.GetTrainingReq.TimestampRange)
    }

    // @@protoc_insertion_point(class_scope:org.example.proto.GetTrainingReq.TimestampRange)
    private static final org.example.proto.GetTrainingReq.TimestampRange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.GetTrainingReq.TimestampRange();
    }

    public static org.example.proto.GetTrainingReq.TimestampRange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimestampRange>
        PARSER = new com.google.protobuf.AbstractParser<TimestampRange>() {
      @java.lang.Override
      public TimestampRange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TimestampRange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimestampRange> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingReq.TimestampRange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int filterCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object filter_;
  public enum FilterCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TIMESTAMP(1),
    RANGE(2),
    FILTER_NOT_SET(0);
    private final int value;
    private FilterCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FilterCase valueOf(int value) {
      return forNumber(value);
    }

    public static FilterCase forNumber(int value) {
      switch (value) {
        case 1: return TIMESTAMP;
        case 2: return RANGE;
        case 0: return FILTER_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FilterCase
  getFilterCase() {
    return FilterCase.forNumber(
        filterCase_);
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 3;
  private long accountId_ = 0L;
  /**
   * <code>int64 account_id = 3;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public long getAccountId() {
    return accountId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  /**
   * <pre>
   * single day
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return filterCase_ == 1;
  }
  /**
   * <pre>
   * single day
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    if (filterCase_ == 1) {
      return (java.lang.Long) filter_;
    }
    return 0L;
  }

  public static final int RANGE_FIELD_NUMBER = 2;
  /**
   * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
   * @return Whether the range field is set.
   */
  @java.lang.Override
  public boolean hasRange() {
    return filterCase_ == 2;
  }
  /**
   * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
   * @return The range.
   */
  @java.lang.Override
  public org.example.proto.GetTrainingReq.TimestampRange getRange() {
    if (filterCase_ == 2) {
       return (org.example.proto.GetTrainingReq.TimestampRange) filter_;
    }
    return org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
  }
  /**
   * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
   */
  @java.lang.Override
  public org.example.proto.GetTrainingReq.TimestampRangeOrBuilder getRangeOrBuilder() {
    if (filterCase_ == 2) {
       return (org.example.proto.GetTrainingReq.TimestampRange) filter_;
    }
    return org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (filterCase_ == 1) {
      output.writeInt64(
          1, (long)((java.lang.Long) filter_));
    }
    if (filterCase_ == 2) {
      output.writeMessage(2, (org.example.proto.GetTrainingReq.TimestampRange) filter_);
    }
    if (accountId_ != 0L) {
      output.writeInt64(3, accountId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (filterCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            1, (long)((java.lang.Long) filter_));
    }
    if (filterCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.example.proto.GetTrainingReq.TimestampRange) filter_);
    }
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, accountId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.GetTrainingReq)) {
      return super.equals(obj);
    }
    org.example.proto.GetTrainingReq other = (org.example.proto.GetTrainingReq) obj;

    if (getAccountId()
        != other.getAccountId()) return false;
    if (!getFilterCase().equals(other.getFilterCase())) return false;
    switch (filterCase_) {
      case 1:
        if (getTimestamp()
            != other.getTimestamp()) return false;
        break;
      case 2:
        if (!getRange()
            .equals(other.getRange())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    switch (filterCase_) {
      case 1:
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
        break;
      case 2:
        hash = (37 * hash) + RANGE_FIELD_NUMBER;
        hash = (53 * hash) + getRange().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.GetTrainingReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.GetTrainingReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.GetTrainingReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.proto.GetTrainingReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.proto.GetTrainingReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.GetTrainingReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.GetTrainingReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.proto.GetTrainingReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.proto.GetTrainingReq)
      org.example.proto.GetTrainingReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.GetTrainingReq.class, org.example.proto.GetTrainingReq.Builder.class);
    }

    // Construct using org.example.proto.GetTrainingReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accountId_ = 0L;
      if (rangeBuilder_ != null) {
        rangeBuilder_.clear();
      }
      filterCase_ = 0;
      filter_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingReq_descriptor;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingReq getDefaultInstanceForType() {
      return org.example.proto.GetTrainingReq.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.GetTrainingReq build() {
      org.example.proto.GetTrainingReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingReq buildPartial() {
      org.example.proto.GetTrainingReq result = new org.example.proto.GetTrainingReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.proto.GetTrainingReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accountId_ = accountId_;
      }
    }

    private void buildPartialOneofs(org.example.proto.GetTrainingReq result) {
      result.filterCase_ = filterCase_;
      result.filter_ = this.filter_;
      if (filterCase_ == 2 &&
          rangeBuilder_ != null) {
        result.filter_ = rangeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.GetTrainingReq) {
        return mergeFrom((org.example.proto.GetTrainingReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.GetTrainingReq other) {
      if (other == org.example.proto.GetTrainingReq.getDefaultInstance()) return this;
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      switch (other.getFilterCase()) {
        case TIMESTAMP: {
          setTimestamp(other.getTimestamp());
          break;
        }
        case RANGE: {
          mergeRange(other.getRange());
          break;
        }
        case FILTER_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              filter_ = input.readInt64();
              filterCase_ = 1;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              filterCase_ = 2;
              break;
            } // case 18
            case 24: {
              accountId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int filterCase_ = 0;
    private java.lang.Object filter_;
    public FilterCase
        getFilterCase() {
      return FilterCase.forNumber(
          filterCase_);
    }

    public Builder clearFilter() {
      filterCase_ = 0;
      filter_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private long accountId_ ;
    /**
     * <code>int64 account_id = 3;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>int64 account_id = 3;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {

      accountId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 account_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accountId_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * single day
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return filterCase_ == 1;
    }
    /**
     * <pre>
     * single day
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      if (filterCase_ == 1) {
        return (java.lang.Long) filter_;
      }
      return 0L;
    }
    /**
     * <pre>
     * single day
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      filterCase_ = 1;
      filter_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * single day
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      if (filterCase_ == 1) {
        filterCase_ = 0;
        filter_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        org.example.proto.GetTrainingReq.TimestampRange, org.example.proto.GetTrainingReq.TimestampRange.Builder, org.example.proto.GetTrainingReq.TimestampRangeOrBuilder> rangeBuilder_;
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     * @return Whether the range field is set.
     */
    @java.lang.Override
    public boolean hasRange() {
      return filterCase_ == 2;
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     * @return The range.
     */
    @java.lang.Override
    public org.example.proto.GetTrainingReq.TimestampRange getRange() {
      if (rangeBuilder_ == null) {
        if (filterCase_ == 2) {
          return (org.example.proto.GetTrainingReq.TimestampRange) filter_;
        }
        return org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
      } else {
        if (filterCase_ == 2) {
          return rangeBuilder_.getMessage();
        }
        return org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
      }
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    public Builder setRange(org.example.proto.GetTrainingReq.TimestampRange value) {
      if (rangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        rangeBuilder_.setMessage(value);
      }
      filterCase_ = 2;
      return this;
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    public Builder setRange(
        org.example.proto.GetTrainingReq.TimestampRange.Builder builderForValue) {
      if (rangeBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        rangeBuilder_.setMessage(builderForValue.build());
      }
      filterCase_ = 2;
      return this;
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    public Builder mergeRange(org.example.proto.GetTrainingReq.TimestampRange value) {
      if (rangeBuilder_ == null) {
        if (filterCase_ == 2 &&
            filter_ != org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance()) {
          filter_ = org.example.proto.GetTrainingReq.TimestampRange.newBuilder((org.example.proto.GetTrainingReq.TimestampRange) filter_)
              .mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        if (filterCase_ == 2) {
          rangeBuilder_.mergeFrom(value);
        } else {
          rangeBuilder_.setMessage(value);
        }
      }
      filterCase_ = 2;
      return this;
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    public Builder clearRange() {
      if (rangeBuilder_ == null) {
        if (filterCase_ == 2) {
          filterCase_ = 0;
          filter_ = null;
          onChanged();
        }
      } else {
        if (filterCase_ == 2) {
          filterCase_ = 0;
          filter_ = null;
        }
        rangeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    public org.example.proto.GetTrainingReq.TimestampRange.Builder getRangeBuilder() {
      return internalGetRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    @java.lang.Override
    public org.example.proto.GetTrainingReq.TimestampRangeOrBuilder getRangeOrBuilder() {
      if ((filterCase_ == 2) && (rangeBuilder_ != null)) {
        return rangeBuilder_.getMessageOrBuilder();
      } else {
        if (filterCase_ == 2) {
          return (org.example.proto.GetTrainingReq.TimestampRange) filter_;
        }
        return org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
      }
    }
    /**
     * <code>.org.example.proto.GetTrainingReq.TimestampRange range = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.example.proto.GetTrainingReq.TimestampRange, org.example.proto.GetTrainingReq.TimestampRange.Builder, org.example.proto.GetTrainingReq.TimestampRangeOrBuilder> 
        internalGetRangeFieldBuilder() {
      if (rangeBuilder_ == null) {
        if (!(filterCase_ == 2)) {
          filter_ = org.example.proto.GetTrainingReq.TimestampRange.getDefaultInstance();
        }
        rangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.example.proto.GetTrainingReq.TimestampRange, org.example.proto.GetTrainingReq.TimestampRange.Builder, org.example.proto.GetTrainingReq.TimestampRangeOrBuilder>(
                (org.example.proto.GetTrainingReq.TimestampRange) filter_,
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      filterCase_ = 2;
      onChanged();
      return rangeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.example.proto.GetTrainingReq)
  }

  // @@protoc_insertion_point(class_scope:org.example.proto.GetTrainingReq)
  private static final org.example.proto.GetTrainingReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.GetTrainingReq();
  }

  public static org.example.proto.GetTrainingReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTrainingReq>
      PARSER = new com.google.protobuf.AbstractParser<GetTrainingReq>() {
    @java.lang.Override
    public GetTrainingReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTrainingReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTrainingReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.GetTrainingReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

