// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

/**
 * Protobuf type {@code org.example.proto.GetTrainingResp}
 */
public final class GetTrainingResp extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.proto.GetTrainingResp)
    GetTrainingRespOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GetTrainingResp.class.getName());
  }
  // Use GetTrainingResp.newBuilder() to construct.
  private GetTrainingResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetTrainingResp() {
    trainings_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.GetTrainingResp.class, org.example.proto.GetTrainingResp.Builder.class);
  }

  public interface ExerciseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.proto.GetTrainingResp.Exercise)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 sort_id = 2;</code>
     * @return The sortId.
     */
    long getSortId();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string target_muscle = 4;</code>
     * @return The targetMuscle.
     */
    java.lang.String getTargetMuscle();
    /**
     * <code>string target_muscle = 4;</code>
     * @return The bytes for targetMuscle.
     */
    com.google.protobuf.ByteString
        getTargetMuscleBytes();
  }
  /**
   * Protobuf type {@code org.example.proto.GetTrainingResp.Exercise}
   */
  public static final class Exercise extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.proto.GetTrainingResp.Exercise)
      ExerciseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Exercise.class.getName());
    }
    // Use Exercise.newBuilder() to construct.
    private Exercise(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Exercise() {
      name_ = "";
      targetMuscle_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Exercise_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Exercise_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.GetTrainingResp.Exercise.class, org.example.proto.GetTrainingResp.Exercise.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int SORT_ID_FIELD_NUMBER = 2;
    private long sortId_ = 0L;
    /**
     * <code>int64 sort_id = 2;</code>
     * @return The sortId.
     */
    @java.lang.Override
    public long getSortId() {
      return sortId_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_MUSCLE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object targetMuscle_ = "";
    /**
     * <code>string target_muscle = 4;</code>
     * @return The targetMuscle.
     */
    @java.lang.Override
    public java.lang.String getTargetMuscle() {
      java.lang.Object ref = targetMuscle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetMuscle_ = s;
        return s;
      }
    }
    /**
     * <code>string target_muscle = 4;</code>
     * @return The bytes for targetMuscle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetMuscleBytes() {
      java.lang.Object ref = targetMuscle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetMuscle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (sortId_ != 0L) {
        output.writeInt64(2, sortId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetMuscle_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, targetMuscle_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (sortId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sortId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetMuscle_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, targetMuscle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.GetTrainingResp.Exercise)) {
        return super.equals(obj);
      }
      org.example.proto.GetTrainingResp.Exercise other = (org.example.proto.GetTrainingResp.Exercise) obj;

      if (getId()
          != other.getId()) return false;
      if (getSortId()
          != other.getSortId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getTargetMuscle()
          .equals(other.getTargetMuscle())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + SORT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSortId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TARGET_MUSCLE_FIELD_NUMBER;
      hash = (53 * hash) + getTargetMuscle().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.proto.GetTrainingResp.Exercise parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.proto.GetTrainingResp.Exercise parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.GetTrainingResp.Exercise parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.GetTrainingResp.Exercise prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.proto.GetTrainingResp.Exercise}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.proto.GetTrainingResp.Exercise)
        org.example.proto.GetTrainingResp.ExerciseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Exercise_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Exercise_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.GetTrainingResp.Exercise.class, org.example.proto.GetTrainingResp.Exercise.Builder.class);
      }

      // Construct using org.example.proto.GetTrainingResp.Exercise.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        sortId_ = 0L;
        name_ = "";
        targetMuscle_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Exercise_descriptor;
      }

      @java.lang.Override
      public org.example.proto.GetTrainingResp.Exercise getDefaultInstanceForType() {
        return org.example.proto.GetTrainingResp.Exercise.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.GetTrainingResp.Exercise build() {
        org.example.proto.GetTrainingResp.Exercise result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.GetTrainingResp.Exercise buildPartial() {
        org.example.proto.GetTrainingResp.Exercise result = new org.example.proto.GetTrainingResp.Exercise(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.proto.GetTrainingResp.Exercise result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sortId_ = sortId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.targetMuscle_ = targetMuscle_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.GetTrainingResp.Exercise) {
          return mergeFrom((org.example.proto.GetTrainingResp.Exercise)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.GetTrainingResp.Exercise other) {
        if (other == org.example.proto.GetTrainingResp.Exercise.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getSortId() != 0L) {
          setSortId(other.getSortId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getTargetMuscle().isEmpty()) {
          targetMuscle_ = other.targetMuscle_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                sortId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                targetMuscle_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long sortId_ ;
      /**
       * <code>int64 sort_id = 2;</code>
       * @return The sortId.
       */
      @java.lang.Override
      public long getSortId() {
        return sortId_;
      }
      /**
       * <code>int64 sort_id = 2;</code>
       * @param value The sortId to set.
       * @return This builder for chaining.
       */
      public Builder setSortId(long value) {

        sortId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sort_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSortId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sortId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object targetMuscle_ = "";
      /**
       * <code>string target_muscle = 4;</code>
       * @return The targetMuscle.
       */
      public java.lang.String getTargetMuscle() {
        java.lang.Object ref = targetMuscle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetMuscle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target_muscle = 4;</code>
       * @return The bytes for targetMuscle.
       */
      public com.google.protobuf.ByteString
          getTargetMuscleBytes() {
        java.lang.Object ref = targetMuscle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetMuscle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target_muscle = 4;</code>
       * @param value The targetMuscle to set.
       * @return This builder for chaining.
       */
      public Builder setTargetMuscle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        targetMuscle_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string target_muscle = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetMuscle() {
        targetMuscle_ = getDefaultInstance().getTargetMuscle();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string target_muscle = 4;</code>
       * @param value The bytes for targetMuscle to set.
       * @return This builder for chaining.
       */
      public Builder setTargetMuscleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        targetMuscle_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.proto.GetTrainingResp.Exercise)
    }

    // @@protoc_insertion_point(class_scope:org.example.proto.GetTrainingResp.Exercise)
    private static final org.example.proto.GetTrainingResp.Exercise DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.GetTrainingResp.Exercise();
    }

    public static org.example.proto.GetTrainingResp.Exercise getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Exercise>
        PARSER = new com.google.protobuf.AbstractParser<Exercise>() {
      @java.lang.Override
      public Exercise parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Exercise> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exercise> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingResp.Exercise getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrainingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.proto.GetTrainingResp.Training)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string category = 3;</code>
     * @return The category.
     */
    java.lang.String getCategory();
    /**
     * <code>string category = 3;</code>
     * @return The bytes for category.
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    java.util.List<org.example.proto.GetTrainingResp.Exercise> 
        getExercisesList();
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    org.example.proto.GetTrainingResp.Exercise getExercises(int index);
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    int getExercisesCount();
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    java.util.List<? extends org.example.proto.GetTrainingResp.ExerciseOrBuilder> 
        getExercisesOrBuilderList();
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    org.example.proto.GetTrainingResp.ExerciseOrBuilder getExercisesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.example.proto.GetTrainingResp.Training}
   */
  public static final class Training extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.proto.GetTrainingResp.Training)
      TrainingOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Training.class.getName());
    }
    // Use Training.newBuilder() to construct.
    private Training(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Training() {
      category_ = "";
      exercises_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Training_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Training_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.GetTrainingResp.Training.class, org.example.proto.GetTrainingResp.Training.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object category_ = "";
    /**
     * <code>string category = 3;</code>
     * @return The category.
     */
    @java.lang.Override
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>string category = 3;</code>
     * @return The bytes for category.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXERCISES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<org.example.proto.GetTrainingResp.Exercise> exercises_;
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    @java.lang.Override
    public java.util.List<org.example.proto.GetTrainingResp.Exercise> getExercisesList() {
      return exercises_;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.example.proto.GetTrainingResp.ExerciseOrBuilder> 
        getExercisesOrBuilderList() {
      return exercises_;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    @java.lang.Override
    public int getExercisesCount() {
      return exercises_.size();
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    @java.lang.Override
    public org.example.proto.GetTrainingResp.Exercise getExercises(int index) {
      return exercises_.get(index);
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
     */
    @java.lang.Override
    public org.example.proto.GetTrainingResp.ExerciseOrBuilder getExercisesOrBuilder(
        int index) {
      return exercises_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, category_);
      }
      for (int i = 0; i < exercises_.size(); i++) {
        output.writeMessage(4, exercises_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(category_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, category_);
      }
      for (int i = 0; i < exercises_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, exercises_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.GetTrainingResp.Training)) {
        return super.equals(obj);
      }
      org.example.proto.GetTrainingResp.Training other = (org.example.proto.GetTrainingResp.Training) obj;

      if (getId()
          != other.getId()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getCategory()
          .equals(other.getCategory())) return false;
      if (!getExercisesList()
          .equals(other.getExercisesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      if (getExercisesCount() > 0) {
        hash = (37 * hash) + EXERCISES_FIELD_NUMBER;
        hash = (53 * hash) + getExercisesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.GetTrainingResp.Training parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.proto.GetTrainingResp.Training parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.proto.GetTrainingResp.Training parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.GetTrainingResp.Training parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.GetTrainingResp.Training prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.proto.GetTrainingResp.Training}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.proto.GetTrainingResp.Training)
        org.example.proto.GetTrainingResp.TrainingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Training_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Training_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.GetTrainingResp.Training.class, org.example.proto.GetTrainingResp.Training.Builder.class);
      }

      // Construct using org.example.proto.GetTrainingResp.Training.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        timestamp_ = 0L;
        category_ = "";
        if (exercisesBuilder_ == null) {
          exercises_ = java.util.Collections.emptyList();
        } else {
          exercises_ = null;
          exercisesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_Training_descriptor;
      }

      @java.lang.Override
      public org.example.proto.GetTrainingResp.Training getDefaultInstanceForType() {
        return org.example.proto.GetTrainingResp.Training.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.GetTrainingResp.Training build() {
        org.example.proto.GetTrainingResp.Training result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.GetTrainingResp.Training buildPartial() {
        org.example.proto.GetTrainingResp.Training result = new org.example.proto.GetTrainingResp.Training(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.example.proto.GetTrainingResp.Training result) {
        if (exercisesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            exercises_ = java.util.Collections.unmodifiableList(exercises_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.exercises_ = exercises_;
        } else {
          result.exercises_ = exercisesBuilder_.build();
        }
      }

      private void buildPartial0(org.example.proto.GetTrainingResp.Training result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.category_ = category_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.GetTrainingResp.Training) {
          return mergeFrom((org.example.proto.GetTrainingResp.Training)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.GetTrainingResp.Training other) {
        if (other == org.example.proto.GetTrainingResp.Training.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (exercisesBuilder_ == null) {
          if (!other.exercises_.isEmpty()) {
            if (exercises_.isEmpty()) {
              exercises_ = other.exercises_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureExercisesIsMutable();
              exercises_.addAll(other.exercises_);
            }
            onChanged();
          }
        } else {
          if (!other.exercises_.isEmpty()) {
            if (exercisesBuilder_.isEmpty()) {
              exercisesBuilder_.dispose();
              exercisesBuilder_ = null;
              exercises_ = other.exercises_;
              bitField0_ = (bitField0_ & ~0x00000008);
              exercisesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetExercisesFieldBuilder() : null;
            } else {
              exercisesBuilder_.addAllMessages(other.exercises_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                category_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                org.example.proto.GetTrainingResp.Exercise m =
                    input.readMessage(
                        org.example.proto.GetTrainingResp.Exercise.parser(),
                        extensionRegistry);
                if (exercisesBuilder_ == null) {
                  ensureExercisesIsMutable();
                  exercises_.add(m);
                } else {
                  exercisesBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>string category = 3;</code>
       * @return The category.
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category = 3;</code>
       * @return The bytes for category.
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category = 3;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        category_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string category = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        category_ = getDefaultInstance().getCategory();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string category = 3;</code>
       * @param value The bytes for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        category_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.util.List<org.example.proto.GetTrainingResp.Exercise> exercises_ =
        java.util.Collections.emptyList();
      private void ensureExercisesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          exercises_ = new java.util.ArrayList<org.example.proto.GetTrainingResp.Exercise>(exercises_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.example.proto.GetTrainingResp.Exercise, org.example.proto.GetTrainingResp.Exercise.Builder, org.example.proto.GetTrainingResp.ExerciseOrBuilder> exercisesBuilder_;

      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public java.util.List<org.example.proto.GetTrainingResp.Exercise> getExercisesList() {
        if (exercisesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exercises_);
        } else {
          return exercisesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public int getExercisesCount() {
        if (exercisesBuilder_ == null) {
          return exercises_.size();
        } else {
          return exercisesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public org.example.proto.GetTrainingResp.Exercise getExercises(int index) {
        if (exercisesBuilder_ == null) {
          return exercises_.get(index);
        } else {
          return exercisesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder setExercises(
          int index, org.example.proto.GetTrainingResp.Exercise value) {
        if (exercisesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExercisesIsMutable();
          exercises_.set(index, value);
          onChanged();
        } else {
          exercisesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder setExercises(
          int index, org.example.proto.GetTrainingResp.Exercise.Builder builderForValue) {
        if (exercisesBuilder_ == null) {
          ensureExercisesIsMutable();
          exercises_.set(index, builderForValue.build());
          onChanged();
        } else {
          exercisesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder addExercises(org.example.proto.GetTrainingResp.Exercise value) {
        if (exercisesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExercisesIsMutable();
          exercises_.add(value);
          onChanged();
        } else {
          exercisesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder addExercises(
          int index, org.example.proto.GetTrainingResp.Exercise value) {
        if (exercisesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExercisesIsMutable();
          exercises_.add(index, value);
          onChanged();
        } else {
          exercisesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder addExercises(
          org.example.proto.GetTrainingResp.Exercise.Builder builderForValue) {
        if (exercisesBuilder_ == null) {
          ensureExercisesIsMutable();
          exercises_.add(builderForValue.build());
          onChanged();
        } else {
          exercisesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder addExercises(
          int index, org.example.proto.GetTrainingResp.Exercise.Builder builderForValue) {
        if (exercisesBuilder_ == null) {
          ensureExercisesIsMutable();
          exercises_.add(index, builderForValue.build());
          onChanged();
        } else {
          exercisesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder addAllExercises(
          java.lang.Iterable<? extends org.example.proto.GetTrainingResp.Exercise> values) {
        if (exercisesBuilder_ == null) {
          ensureExercisesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exercises_);
          onChanged();
        } else {
          exercisesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder clearExercises() {
        if (exercisesBuilder_ == null) {
          exercises_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          exercisesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public Builder removeExercises(int index) {
        if (exercisesBuilder_ == null) {
          ensureExercisesIsMutable();
          exercises_.remove(index);
          onChanged();
        } else {
          exercisesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public org.example.proto.GetTrainingResp.Exercise.Builder getExercisesBuilder(
          int index) {
        return internalGetExercisesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public org.example.proto.GetTrainingResp.ExerciseOrBuilder getExercisesOrBuilder(
          int index) {
        if (exercisesBuilder_ == null) {
          return exercises_.get(index);  } else {
          return exercisesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public java.util.List<? extends org.example.proto.GetTrainingResp.ExerciseOrBuilder> 
           getExercisesOrBuilderList() {
        if (exercisesBuilder_ != null) {
          return exercisesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exercises_);
        }
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public org.example.proto.GetTrainingResp.Exercise.Builder addExercisesBuilder() {
        return internalGetExercisesFieldBuilder().addBuilder(
            org.example.proto.GetTrainingResp.Exercise.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public org.example.proto.GetTrainingResp.Exercise.Builder addExercisesBuilder(
          int index) {
        return internalGetExercisesFieldBuilder().addBuilder(
            index, org.example.proto.GetTrainingResp.Exercise.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.proto.GetTrainingResp.Exercise exercises = 4;</code>
       */
      public java.util.List<org.example.proto.GetTrainingResp.Exercise.Builder> 
           getExercisesBuilderList() {
        return internalGetExercisesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.example.proto.GetTrainingResp.Exercise, org.example.proto.GetTrainingResp.Exercise.Builder, org.example.proto.GetTrainingResp.ExerciseOrBuilder> 
          internalGetExercisesFieldBuilder() {
        if (exercisesBuilder_ == null) {
          exercisesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.example.proto.GetTrainingResp.Exercise, org.example.proto.GetTrainingResp.Exercise.Builder, org.example.proto.GetTrainingResp.ExerciseOrBuilder>(
                  exercises_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          exercises_ = null;
        }
        return exercisesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.example.proto.GetTrainingResp.Training)
    }

    // @@protoc_insertion_point(class_scope:org.example.proto.GetTrainingResp.Training)
    private static final org.example.proto.GetTrainingResp.Training DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.GetTrainingResp.Training();
    }

    public static org.example.proto.GetTrainingResp.Training getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Training>
        PARSER = new com.google.protobuf.AbstractParser<Training>() {
      @java.lang.Override
      public Training parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Training> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Training> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingResp.Training getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TRAININGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.example.proto.GetTrainingResp.Training> trainings_;
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.proto.GetTrainingResp.Training> getTrainingsList() {
    return trainings_;
  }
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.proto.GetTrainingResp.TrainingOrBuilder> 
      getTrainingsOrBuilderList() {
    return trainings_;
  }
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  @java.lang.Override
  public int getTrainingsCount() {
    return trainings_.size();
  }
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  @java.lang.Override
  public org.example.proto.GetTrainingResp.Training getTrainings(int index) {
    return trainings_.get(index);
  }
  /**
   * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
   */
  @java.lang.Override
  public org.example.proto.GetTrainingResp.TrainingOrBuilder getTrainingsOrBuilder(
      int index) {
    return trainings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < trainings_.size(); i++) {
      output.writeMessage(1, trainings_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < trainings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, trainings_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.GetTrainingResp)) {
      return super.equals(obj);
    }
    org.example.proto.GetTrainingResp other = (org.example.proto.GetTrainingResp) obj;

    if (!getTrainingsList()
        .equals(other.getTrainingsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTrainingsCount() > 0) {
      hash = (37 * hash) + TRAININGS_FIELD_NUMBER;
      hash = (53 * hash) + getTrainingsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.GetTrainingResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.GetTrainingResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.GetTrainingResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.proto.GetTrainingResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.proto.GetTrainingResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.GetTrainingResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.GetTrainingResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.proto.GetTrainingResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.proto.GetTrainingResp)
      org.example.proto.GetTrainingRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.GetTrainingResp.class, org.example.proto.GetTrainingResp.Builder.class);
    }

    // Construct using org.example.proto.GetTrainingResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (trainingsBuilder_ == null) {
        trainings_ = java.util.Collections.emptyList();
      } else {
        trainings_ = null;
        trainingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.Trainings.internal_static_org_example_proto_GetTrainingResp_descriptor;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingResp getDefaultInstanceForType() {
      return org.example.proto.GetTrainingResp.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.GetTrainingResp build() {
      org.example.proto.GetTrainingResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.GetTrainingResp buildPartial() {
      org.example.proto.GetTrainingResp result = new org.example.proto.GetTrainingResp(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.proto.GetTrainingResp result) {
      if (trainingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trainings_ = java.util.Collections.unmodifiableList(trainings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trainings_ = trainings_;
      } else {
        result.trainings_ = trainingsBuilder_.build();
      }
    }

    private void buildPartial0(org.example.proto.GetTrainingResp result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.GetTrainingResp) {
        return mergeFrom((org.example.proto.GetTrainingResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.GetTrainingResp other) {
      if (other == org.example.proto.GetTrainingResp.getDefaultInstance()) return this;
      if (trainingsBuilder_ == null) {
        if (!other.trainings_.isEmpty()) {
          if (trainings_.isEmpty()) {
            trainings_ = other.trainings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTrainingsIsMutable();
            trainings_.addAll(other.trainings_);
          }
          onChanged();
        }
      } else {
        if (!other.trainings_.isEmpty()) {
          if (trainingsBuilder_.isEmpty()) {
            trainingsBuilder_.dispose();
            trainingsBuilder_ = null;
            trainings_ = other.trainings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            trainingsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTrainingsFieldBuilder() : null;
          } else {
            trainingsBuilder_.addAllMessages(other.trainings_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.example.proto.GetTrainingResp.Training m =
                  input.readMessage(
                      org.example.proto.GetTrainingResp.Training.parser(),
                      extensionRegistry);
              if (trainingsBuilder_ == null) {
                ensureTrainingsIsMutable();
                trainings_.add(m);
              } else {
                trainingsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.example.proto.GetTrainingResp.Training> trainings_ =
      java.util.Collections.emptyList();
    private void ensureTrainingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trainings_ = new java.util.ArrayList<org.example.proto.GetTrainingResp.Training>(trainings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.proto.GetTrainingResp.Training, org.example.proto.GetTrainingResp.Training.Builder, org.example.proto.GetTrainingResp.TrainingOrBuilder> trainingsBuilder_;

    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public java.util.List<org.example.proto.GetTrainingResp.Training> getTrainingsList() {
      if (trainingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trainings_);
      } else {
        return trainingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public int getTrainingsCount() {
      if (trainingsBuilder_ == null) {
        return trainings_.size();
      } else {
        return trainingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public org.example.proto.GetTrainingResp.Training getTrainings(int index) {
      if (trainingsBuilder_ == null) {
        return trainings_.get(index);
      } else {
        return trainingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder setTrainings(
        int index, org.example.proto.GetTrainingResp.Training value) {
      if (trainingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrainingsIsMutable();
        trainings_.set(index, value);
        onChanged();
      } else {
        trainingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder setTrainings(
        int index, org.example.proto.GetTrainingResp.Training.Builder builderForValue) {
      if (trainingsBuilder_ == null) {
        ensureTrainingsIsMutable();
        trainings_.set(index, builderForValue.build());
        onChanged();
      } else {
        trainingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder addTrainings(org.example.proto.GetTrainingResp.Training value) {
      if (trainingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrainingsIsMutable();
        trainings_.add(value);
        onChanged();
      } else {
        trainingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder addTrainings(
        int index, org.example.proto.GetTrainingResp.Training value) {
      if (trainingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrainingsIsMutable();
        trainings_.add(index, value);
        onChanged();
      } else {
        trainingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder addTrainings(
        org.example.proto.GetTrainingResp.Training.Builder builderForValue) {
      if (trainingsBuilder_ == null) {
        ensureTrainingsIsMutable();
        trainings_.add(builderForValue.build());
        onChanged();
      } else {
        trainingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder addTrainings(
        int index, org.example.proto.GetTrainingResp.Training.Builder builderForValue) {
      if (trainingsBuilder_ == null) {
        ensureTrainingsIsMutable();
        trainings_.add(index, builderForValue.build());
        onChanged();
      } else {
        trainingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder addAllTrainings(
        java.lang.Iterable<? extends org.example.proto.GetTrainingResp.Training> values) {
      if (trainingsBuilder_ == null) {
        ensureTrainingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trainings_);
        onChanged();
      } else {
        trainingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder clearTrainings() {
      if (trainingsBuilder_ == null) {
        trainings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        trainingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public Builder removeTrainings(int index) {
      if (trainingsBuilder_ == null) {
        ensureTrainingsIsMutable();
        trainings_.remove(index);
        onChanged();
      } else {
        trainingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public org.example.proto.GetTrainingResp.Training.Builder getTrainingsBuilder(
        int index) {
      return internalGetTrainingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public org.example.proto.GetTrainingResp.TrainingOrBuilder getTrainingsOrBuilder(
        int index) {
      if (trainingsBuilder_ == null) {
        return trainings_.get(index);  } else {
        return trainingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public java.util.List<? extends org.example.proto.GetTrainingResp.TrainingOrBuilder> 
         getTrainingsOrBuilderList() {
      if (trainingsBuilder_ != null) {
        return trainingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trainings_);
      }
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public org.example.proto.GetTrainingResp.Training.Builder addTrainingsBuilder() {
      return internalGetTrainingsFieldBuilder().addBuilder(
          org.example.proto.GetTrainingResp.Training.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public org.example.proto.GetTrainingResp.Training.Builder addTrainingsBuilder(
        int index) {
      return internalGetTrainingsFieldBuilder().addBuilder(
          index, org.example.proto.GetTrainingResp.Training.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.proto.GetTrainingResp.Training trainings = 1;</code>
     */
    public java.util.List<org.example.proto.GetTrainingResp.Training.Builder> 
         getTrainingsBuilderList() {
      return internalGetTrainingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.proto.GetTrainingResp.Training, org.example.proto.GetTrainingResp.Training.Builder, org.example.proto.GetTrainingResp.TrainingOrBuilder> 
        internalGetTrainingsFieldBuilder() {
      if (trainingsBuilder_ == null) {
        trainingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.example.proto.GetTrainingResp.Training, org.example.proto.GetTrainingResp.Training.Builder, org.example.proto.GetTrainingResp.TrainingOrBuilder>(
                trainings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trainings_ = null;
      }
      return trainingsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.example.proto.GetTrainingResp)
  }

  // @@protoc_insertion_point(class_scope:org.example.proto.GetTrainingResp)
  private static final org.example.proto.GetTrainingResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.GetTrainingResp();
  }

  public static org.example.proto.GetTrainingResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTrainingResp>
      PARSER = new com.google.protobuf.AbstractParser<GetTrainingResp>() {
    @java.lang.Override
    public GetTrainingResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTrainingResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTrainingResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.GetTrainingResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

