// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greeter.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

import io.grpc.stub.ClientCalls;

import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

/**
 * <pre>
 * The greeting service definition.
 * </pre>
 *
 * Protobuf service {@code asd.Greeter}
 */
public  abstract class Greeter
    implements com.google.protobuf.Service {
  protected Greeter() {}

  public interface Interface {
    /**
     * <pre>
     * Sends a greeting
     * </pre>
     *
     * <code>rpc SayHello(.asd.HelloRequest) returns (.asd.HelloReply);</code>
     */
    public abstract void sayHello(
        com.google.protobuf.RpcController controller,
        org.example.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<org.example.proto.HelloReply> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new Greeter() {
      @java.lang.Override
      public  void sayHello(
          com.google.protobuf.RpcController controller,
          org.example.proto.HelloRequest request,
          com.google.protobuf.RpcCallback<org.example.proto.HelloReply> done) {
        impl.sayHello(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sayHello(controller, (org.example.proto.HelloRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return org.example.proto.HelloRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return org.example.proto.HelloReply.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * Sends a greeting
   * </pre>
   *
   * <code>rpc SayHello(.asd.HelloRequest) returns (.asd.HelloReply);</code>
   */
  public abstract void sayHello(
      com.google.protobuf.RpcController controller,
      org.example.proto.HelloRequest request,
      com.google.protobuf.RpcCallback<org.example.proto.HelloReply> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return org.example.proto.GreeterOuterClass.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sayHello(controller, (org.example.proto.HelloRequest)request,
          com.google.protobuf.RpcUtil.<org.example.proto.HelloReply>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return org.example.proto.HelloRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return org.example.proto.HelloReply.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends org.example.proto.Greeter implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sayHello(
        com.google.protobuf.RpcController controller,
        org.example.proto.HelloRequest request,
        com.google.protobuf.RpcCallback<org.example.proto.HelloReply> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        org.example.proto.HelloReply.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          org.example.proto.HelloReply.class,
          org.example.proto.HelloReply.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public org.example.proto.HelloReply sayHello(
        com.google.protobuf.RpcController controller,
        org.example.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public org.example.proto.HelloReply sayHello(
        com.google.protobuf.RpcController controller,
        org.example.proto.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (org.example.proto.HelloReply) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        org.example.proto.HelloReply.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:asd.Greeter)

    /**
     * <pre>
     * The greeting service definition.
     * </pre>
     */
    @javax.annotation.Generated(
        value = "by gRPC proto compiler (version 1.9.1)",
        comments = "Source: greeter.proto")
    public static final class GreeterGrpc {

      private GreeterGrpc() {}

      public static final String SERVICE_NAME = "asd.Greeter";

      // Static method descriptors that strictly reflect the proto.
      @io.grpc.ExperimentalApi("https://github.com/grpc/grpc-java/issues/1901")
      @Deprecated // Use {@link #getSayHelloMethod()} instead.
      public static final io.grpc.MethodDescriptor<HelloRequest,
          HelloReply> METHOD_SAY_HELLO = getSayHelloMethod();

      private static volatile io.grpc.MethodDescriptor<HelloRequest,
          HelloReply> getSayHelloMethod;

      @io.grpc.ExperimentalApi("https://github.com/grpc/grpc-java/issues/1901")
      public static io.grpc.MethodDescriptor<HelloRequest,
          HelloReply> getSayHelloMethod() {
        io.grpc.MethodDescriptor<HelloRequest, HelloReply> getSayHelloMethod;
        if ((getSayHelloMethod = GreeterGrpc.getSayHelloMethod) == null) {
          synchronized (GreeterGrpc.class) {
            if ((getSayHelloMethod = GreeterGrpc.getSayHelloMethod) == null) {
              GreeterGrpc.getSayHelloMethod = getSayHelloMethod =
                  io.grpc.MethodDescriptor.<HelloRequest, HelloReply>newBuilder()
                  .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
                  .setFullMethodName(generateFullMethodName(
                      "asd.Greeter", "SayHello"))
                  .setSampledToLocalTracing(true)
                  .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                      HelloRequest.getDefaultInstance()))
                  .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                      HelloReply.getDefaultInstance()))
                      .setSchemaDescriptor(new GreeterMethodDescriptorSupplier("SayHello"))
                      .build();
              }
            }
         }
         return getSayHelloMethod;
      }

      /**
       * Creates a new async stub that supports all call types for the service
       */
      public static GreeterStub newStub(io.grpc.Channel channel) {
        return new GreeterStub(channel);
      }

      /**
       * Creates a new blocking-style stub that supports unary and streaming output calls on the service
       */
      public static GreeterBlockingStub newBlockingStub(
          io.grpc.Channel channel) {
        return new GreeterBlockingStub(channel);
      }

      /**
       * Creates a new ListenableFuture-style stub that supports unary calls on the service
       */
      public static GreeterFutureStub newFutureStub(
          io.grpc.Channel channel) {
        return new GreeterFutureStub(channel);
      }

      /**
       * <pre>
       * The greeting service definition.
       * </pre>
       */
      public static abstract class GreeterImplBase implements io.grpc.BindableService {

        /**
         * <pre>
         * Sends a greeting
         * </pre>
         */
        public void sayHello(HelloRequest request,
                             io.grpc.stub.StreamObserver<HelloReply> responseObserver) {
          asyncUnimplementedUnaryCall(getSayHelloMethod(), responseObserver);
        }

        @Override public final io.grpc.ServerServiceDefinition bindService() {
          return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
              .addMethod(
                getSayHelloMethod(),
                asyncUnaryCall(
                  new MethodHandlers<
                    HelloRequest,
                    HelloReply>(
                      this, METHODID_SAY_HELLO)))
              .build();
        }
      }

      /**
       * <pre>
       * The greeting service definition.
       * </pre>
       */
      public static final class GreeterStub extends io.grpc.stub.AbstractStub<GreeterStub> {
        private GreeterStub(io.grpc.Channel channel) {
          super(channel);
        }

        private GreeterStub(io.grpc.Channel channel,
            io.grpc.CallOptions callOptions) {
          super(channel, callOptions);
        }

        @Override
        protected GreeterStub build(io.grpc.Channel channel,
                                    io.grpc.CallOptions callOptions) {
          return new GreeterStub(channel, callOptions);
        }

        /**
         * <pre>
         * Sends a greeting
         * </pre>
         */
        public void sayHello(HelloRequest request,
                             io.grpc.stub.StreamObserver<HelloReply> responseObserver) {
          ClientCalls.asyncUnaryCall(
              getChannel().newCall(getSayHelloMethod(), getCallOptions()), request, responseObserver);
        }
      }

      /**
       * <pre>
       * The greeting service definition.
       * </pre>
       */
      public static final class GreeterBlockingStub extends io.grpc.stub.AbstractStub<GreeterBlockingStub> {
        private GreeterBlockingStub(io.grpc.Channel channel) {
          super(channel);
        }

        private GreeterBlockingStub(io.grpc.Channel channel,
            io.grpc.CallOptions callOptions) {
          super(channel, callOptions);
        }

        @Override
        protected GreeterBlockingStub build(io.grpc.Channel channel,
                                            io.grpc.CallOptions callOptions) {
          return new GreeterBlockingStub(channel, callOptions);
        }

        /**
         * <pre>
         * Sends a greeting
         * </pre>
         */
        public HelloReply sayHello(HelloRequest request) {
          return blockingUnaryCall(
              getChannel(), getSayHelloMethod(), getCallOptions(), request);
        }
      }

      /**
       * <pre>
       * The greeting service definition.
       * </pre>
       */
      public static final class GreeterFutureStub extends io.grpc.stub.AbstractStub<GreeterFutureStub> {
        private GreeterFutureStub(io.grpc.Channel channel) {
          super(channel);
        }

        private GreeterFutureStub(io.grpc.Channel channel,
            io.grpc.CallOptions callOptions) {
          super(channel, callOptions);
        }

        @Override
        protected GreeterFutureStub build(io.grpc.Channel channel,
                                          io.grpc.CallOptions callOptions) {
          return new GreeterFutureStub(channel, callOptions);
        }

        /**
         * <pre>
         * Sends a greeting
         * </pre>
         */
        public com.google.common.util.concurrent.ListenableFuture<HelloReply> sayHello(
            HelloRequest request) {
          return futureUnaryCall(
              getChannel().newCall(getSayHelloMethod(), getCallOptions()), request);
        }
      }

      private static final int METHODID_SAY_HELLO = 0;

      private static final class MethodHandlers<Req, Resp> implements
          io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
          io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
          io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
          io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
        private final GreeterImplBase serviceImpl;
        private final int methodId;

        MethodHandlers(GreeterImplBase serviceImpl, int methodId) {
          this.serviceImpl = serviceImpl;
          this.methodId = methodId;
        }

        @Override
        @SuppressWarnings("unchecked")
        public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
          switch (methodId) {
            case METHODID_SAY_HELLO:
              serviceImpl.sayHello((HelloRequest) request,
                  (io.grpc.stub.StreamObserver<HelloReply>) responseObserver);
              break;
            default:
              throw new AssertionError();
          }
        }

        @Override
        @SuppressWarnings("unchecked")
        public io.grpc.stub.StreamObserver<Req> invoke(
            io.grpc.stub.StreamObserver<Resp> responseObserver) {
          switch (methodId) {
            default:
              throw new AssertionError();
          }
        }
      }

      private static abstract class GreeterBaseDescriptorSupplier
          implements io.grpc.protobuf.ProtoFileDescriptorSupplier, io.grpc.protobuf.ProtoServiceDescriptorSupplier {
        GreeterBaseDescriptorSupplier() {}

        @Override
        public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
          return GreeterOuterClass.getDescriptor();
        }

        @Override
        public com.google.protobuf.Descriptors.ServiceDescriptor getServiceDescriptor() {
          return getFileDescriptor().findServiceByName("Greeter");
        }
      }

      private static final class GreeterFileDescriptorSupplier
          extends GreeterBaseDescriptorSupplier {
        GreeterFileDescriptorSupplier() {}
      }

      private static final class GreeterMethodDescriptorSupplier
          extends GreeterBaseDescriptorSupplier
          implements io.grpc.protobuf.ProtoMethodDescriptorSupplier {
        private final String methodName;

        GreeterMethodDescriptorSupplier(String methodName) {
          this.methodName = methodName;
        }

        @Override
        public com.google.protobuf.Descriptors.MethodDescriptor getMethodDescriptor() {
          return getServiceDescriptor().findMethodByName(methodName);
        }
      }

      private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

      public static io.grpc.ServiceDescriptor getServiceDescriptor() {
        io.grpc.ServiceDescriptor result = serviceDescriptor;
        if (result == null) {
          synchronized (GreeterGrpc.class) {
            result = serviceDescriptor;
            if (result == null) {
              serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
                  .setSchemaDescriptor(new GreeterFileDescriptorSupplier())
                  .addMethod(getSayHelloMethod())
                  .build();
            }
          }
        }
        return result;
      }
    }
}

