// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public interface RemoveExerciseReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.proto.RemoveExerciseReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 account_id = 1;</code>
   * @return The accountId.
   */
  long getAccountId();

  /**
   * <code>int64 training_id = 2;</code>
   * @return The trainingId.
   */
  long getTrainingId();

  /**
   * <code>int64 exercise_id = 3;</code>
   * @return The exerciseId.
   */
  long getExerciseId();
}
