// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

/**
 * Protobuf type {@code org.example.proto.RemoveExerciseReq}
 */
public final class RemoveExerciseReq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.proto.RemoveExerciseReq)
    RemoveExerciseReqOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      RemoveExerciseReq.class.getName());
  }
  // Use RemoveExerciseReq.newBuilder() to construct.
  private RemoveExerciseReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RemoveExerciseReq() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.Trainings.internal_static_org_example_proto_RemoveExerciseReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.Trainings.internal_static_org_example_proto_RemoveExerciseReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.RemoveExerciseReq.class, org.example.proto.RemoveExerciseReq.Builder.class);
  }

  public static final int TRAINING_ID_FIELD_NUMBER = 1;
  private long trainingId_ = 0L;
  /**
   * <code>int64 training_id = 1;</code>
   * @return The trainingId.
   */
  @java.lang.Override
  public long getTrainingId() {
    return trainingId_;
  }

  public static final int WORKOUT_EXERCISE_ID_FIELD_NUMBER = 2;
  private long workoutExerciseId_ = 0L;
  /**
   * <code>int64 workout_exercise_id = 2;</code>
   * @return The workoutExerciseId.
   */
  @java.lang.Override
  public long getWorkoutExerciseId() {
    return workoutExerciseId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trainingId_ != 0L) {
      output.writeInt64(1, trainingId_);
    }
    if (workoutExerciseId_ != 0L) {
      output.writeInt64(2, workoutExerciseId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trainingId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, trainingId_);
    }
    if (workoutExerciseId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, workoutExerciseId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.RemoveExerciseReq)) {
      return super.equals(obj);
    }
    org.example.proto.RemoveExerciseReq other = (org.example.proto.RemoveExerciseReq) obj;

    if (getTrainingId()
        != other.getTrainingId()) return false;
    if (getWorkoutExerciseId()
        != other.getWorkoutExerciseId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAINING_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTrainingId());
    hash = (37 * hash) + WORKOUT_EXERCISE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkoutExerciseId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.RemoveExerciseReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.proto.RemoveExerciseReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.proto.RemoveExerciseReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.RemoveExerciseReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.RemoveExerciseReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.proto.RemoveExerciseReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.proto.RemoveExerciseReq)
      org.example.proto.RemoveExerciseReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Trainings.internal_static_org_example_proto_RemoveExerciseReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Trainings.internal_static_org_example_proto_RemoveExerciseReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.RemoveExerciseReq.class, org.example.proto.RemoveExerciseReq.Builder.class);
    }

    // Construct using org.example.proto.RemoveExerciseReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trainingId_ = 0L;
      workoutExerciseId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.Trainings.internal_static_org_example_proto_RemoveExerciseReq_descriptor;
    }

    @java.lang.Override
    public org.example.proto.RemoveExerciseReq getDefaultInstanceForType() {
      return org.example.proto.RemoveExerciseReq.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.RemoveExerciseReq build() {
      org.example.proto.RemoveExerciseReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.RemoveExerciseReq buildPartial() {
      org.example.proto.RemoveExerciseReq result = new org.example.proto.RemoveExerciseReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.proto.RemoveExerciseReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trainingId_ = trainingId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.workoutExerciseId_ = workoutExerciseId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.RemoveExerciseReq) {
        return mergeFrom((org.example.proto.RemoveExerciseReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.RemoveExerciseReq other) {
      if (other == org.example.proto.RemoveExerciseReq.getDefaultInstance()) return this;
      if (other.getTrainingId() != 0L) {
        setTrainingId(other.getTrainingId());
      }
      if (other.getWorkoutExerciseId() != 0L) {
        setWorkoutExerciseId(other.getWorkoutExerciseId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              trainingId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              workoutExerciseId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long trainingId_ ;
    /**
     * <code>int64 training_id = 1;</code>
     * @return The trainingId.
     */
    @java.lang.Override
    public long getTrainingId() {
      return trainingId_;
    }
    /**
     * <code>int64 training_id = 1;</code>
     * @param value The trainingId to set.
     * @return This builder for chaining.
     */
    public Builder setTrainingId(long value) {

      trainingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 training_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrainingId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trainingId_ = 0L;
      onChanged();
      return this;
    }

    private long workoutExerciseId_ ;
    /**
     * <code>int64 workout_exercise_id = 2;</code>
     * @return The workoutExerciseId.
     */
    @java.lang.Override
    public long getWorkoutExerciseId() {
      return workoutExerciseId_;
    }
    /**
     * <code>int64 workout_exercise_id = 2;</code>
     * @param value The workoutExerciseId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkoutExerciseId(long value) {

      workoutExerciseId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 workout_exercise_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkoutExerciseId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      workoutExerciseId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.example.proto.RemoveExerciseReq)
  }

  // @@protoc_insertion_point(class_scope:org.example.proto.RemoveExerciseReq)
  private static final org.example.proto.RemoveExerciseReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.RemoveExerciseReq();
  }

  public static org.example.proto.RemoveExerciseReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoveExerciseReq>
      PARSER = new com.google.protobuf.AbstractParser<RemoveExerciseReq>() {
    @java.lang.Override
    public RemoveExerciseReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RemoveExerciseReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoveExerciseReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.RemoveExerciseReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

