// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trainings.proto
// Protobuf Java Version: 4.30.2

package org.example.proto;

public final class Trainings {
  private Trainings() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Trainings.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_CreateExercise_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_CreateExercise_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_CreateTrainingReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_CreateTrainingReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_GetTrainingReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_GetTrainingReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_GetTrainingReq_TimestampRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_GetTrainingReq_TimestampRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_GetTrainingResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_GetTrainingResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_GetTrainingResp_Exercise_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_GetTrainingResp_Exercise_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_GetTrainingResp_Training_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_GetTrainingResp_Training_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_AddExerciseReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_AddExerciseReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_AddExerciseResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_AddExerciseResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_RemoveExerciseReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_proto_RemoveExerciseReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017trainings.proto\022\021org.example.proto\"\007\n\005" +
      "Empty\"6\n\016CreateExercise\022\017\n\007sort_id\030\001 \001(\003" +
      "\022\023\n\013exercise_id\030\002 \001(\003\"\202\001\n\021CreateTraining" +
      "Req\022\022\n\naccount_id\030\001 \001(\003\022\021\n\ttimestamp\030\002 \001" +
      "(\003\022\020\n\010category\030\003 \001(\t\0224\n\texercises\030\004 \003(\0132" +
      "!.org.example.proto.CreateExercise\"\262\001\n\016G" +
      "etTrainingReq\022\022\n\naccount_id\030\003 \001(\003\022\023\n\ttim" +
      "estamp\030\001 \001(\003H\000\022A\n\005range\030\002 \001(\01320.org.exam" +
      "ple.proto.GetTrainingReq.TimestampRangeH" +
      "\000\032*\n\016TimestampRange\022\014\n\004from\030\001 \001(\003\022\n\n\002to\030" +
      "\002 \001(\003B\010\n\006filter\"\234\002\n\017GetTrainingResp\022>\n\tt" +
      "rainings\030\001 \003(\0132+.org.example.proto.GetTr" +
      "ainingResp.Training\032L\n\010Exercise\022\n\n\002id\030\001 " +
      "\001(\003\022\017\n\007sort_id\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\025\n\rta" +
      "rget_muscle\030\004 \001(\t\032{\n\010Training\022\n\n\002id\030\001 \001(" +
      "\003\022\021\n\ttimestamp\030\002 \001(\003\022\020\n\010category\030\003 \001(\t\022>" +
      "\n\texercises\030\004 \003(\0132+.org.example.proto.Ge" +
      "tTrainingResp.Exercise\"_\n\016AddExerciseReq" +
      "\022\022\n\naccount_id\030\001 \001(\003\022\023\n\013training_id\030\002 \001(" +
      "\003\022\023\n\013exercise_id\030\003 \001(\003\022\017\n\007sort_id\030\004 \001(\003\"" +
      "&\n\017AddExerciseResp\022\023\n\013exercise_id\030\001 \001(\003\"" +
      "Q\n\021RemoveExerciseReq\022\022\n\naccount_id\030\001 \001(\003" +
      "\022\023\n\013training_id\030\002 \001(\003\022\023\n\013exercise_id\030\003 \001" +
      "(\0032\370\002\n\020TrainingsService\022P\n\016CreateTrainin" +
      "g\022$.org.example.proto.CreateTrainingReq\032" +
      "\030.org.example.proto.Empty\022T\n\013GetTraining" +
      "\022!.org.example.proto.GetTrainingReq\032\".or" +
      "g.example.proto.GetTrainingResp\022^\n\025AddEx" +
      "erciseToTraining\022!.org.example.proto.Add" +
      "ExerciseReq\032\".org.example.proto.AddExerc" +
      "iseResp\022\\\n\032RemoveExerciseFromTraining\022$." +
      "org.example.proto.RemoveExerciseReq\032\030.or" +
      "g.example.proto.EmptyB\025\n\021org.example.pro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_proto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_proto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_org_example_proto_CreateExercise_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_proto_CreateExercise_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_CreateExercise_descriptor,
        new java.lang.String[] { "SortId", "ExerciseId", });
    internal_static_org_example_proto_CreateTrainingReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_proto_CreateTrainingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_CreateTrainingReq_descriptor,
        new java.lang.String[] { "AccountId", "Timestamp", "Category", "Exercises", });
    internal_static_org_example_proto_GetTrainingReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_proto_GetTrainingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_GetTrainingReq_descriptor,
        new java.lang.String[] { "AccountId", "Timestamp", "Range", "Filter", });
    internal_static_org_example_proto_GetTrainingReq_TimestampRange_descriptor =
      internal_static_org_example_proto_GetTrainingReq_descriptor.getNestedTypes().get(0);
    internal_static_org_example_proto_GetTrainingReq_TimestampRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_GetTrainingReq_TimestampRange_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_org_example_proto_GetTrainingResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_example_proto_GetTrainingResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_GetTrainingResp_descriptor,
        new java.lang.String[] { "Trainings", });
    internal_static_org_example_proto_GetTrainingResp_Exercise_descriptor =
      internal_static_org_example_proto_GetTrainingResp_descriptor.getNestedTypes().get(0);
    internal_static_org_example_proto_GetTrainingResp_Exercise_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_GetTrainingResp_Exercise_descriptor,
        new java.lang.String[] { "Id", "SortId", "Name", "TargetMuscle", });
    internal_static_org_example_proto_GetTrainingResp_Training_descriptor =
      internal_static_org_example_proto_GetTrainingResp_descriptor.getNestedTypes().get(1);
    internal_static_org_example_proto_GetTrainingResp_Training_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_GetTrainingResp_Training_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "Category", "Exercises", });
    internal_static_org_example_proto_AddExerciseReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_example_proto_AddExerciseReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_AddExerciseReq_descriptor,
        new java.lang.String[] { "AccountId", "TrainingId", "ExerciseId", "SortId", });
    internal_static_org_example_proto_AddExerciseResp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_example_proto_AddExerciseResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_AddExerciseResp_descriptor,
        new java.lang.String[] { "ExerciseId", });
    internal_static_org_example_proto_RemoveExerciseReq_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_example_proto_RemoveExerciseReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_proto_RemoveExerciseReq_descriptor,
        new java.lang.String[] { "AccountId", "TrainingId", "ExerciseId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
